# Generated by Django 2.2.4 on 2019-08-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190604_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='is_loggedin',
            field=models.BooleanField(default=0),
        ),
    ]
